security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Acme\MainBundle\Entity\Usuario: 
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
            
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
            #users:
                #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: Acme\MainBundle\Entity\Usuario, property: usuario }
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
        #dev:
            #pattern:  ^/(_(profiler|wdt)|css|images|js)/
            #security: false

        #login:
            #pattern:  ^/demo/secured/login$
            #security: false

        #secured_area:
            #pattern:    ^/demo/secured/
            #form_login:
                #check_path: /demo/secured/login_check
                #login_path: /demo/secured/login
            #logout:
                #path:   /demo/secured/logout
                #target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /test, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

