MainBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MainBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: AcmeMainBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
AcmeAnnotations:
    resource: "@AcmeMainBundle/Controller/"
    prefix:   /
    type:     annotation
    